<?php

namespace Database\Seeders;

use App\Models\Player;
use Illuminate\Database\Seeder;

class PlayerDescriptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $descriptions = $this->getDescriptions();
        $updatedCount = 0;

        foreach ($descriptions as $name => $description) {
            $updated = Player::where('name', $name)->update(['description' => $description]);
            if ($updated) $updatedCount++;
        }

        $this->command->info("Updated {$updatedCount} player descriptions.");
    }

    /**
     * Get player descriptions.
     */
    private function getDescriptions(): array
    {
        return [
            'B Bonds' => "Barry Bonds is considered one of the greatest baseball players of all time and holds the all-time record for career home runs with 762. A 14-time All-Star and 7-time National League MVP (the most in history), Bonds combined elite power with exceptional plate discipline, drawing a record 2,558 career walks.\n\nPlaying primarily for the Pittsburgh Pirates and San Francisco Giants, Bonds was a complete player who won 8 Gold Glove awards for his defense in left field. His career .444 on-base percentage is the highest in MLB history, and his single-season record of 73 home runs in 2001 still stands.\n\nDespite his remarkable achievements, Bonds' legacy is complicated by his association with performance-enhancing drugs during the BALCO scandal. He has not been inducted into the Baseball Hall of Fame, though his on-field accomplishments rank among the greatest in baseball history.",

            'H Aaron' => "Henry \"Hank\" Aaron, known as \"Hammerin' Hank,\" held the all-time home run record of 755 for 33 years until Barry Bonds surpassed it in 2007. Aaron's consistency was legendary—he never hit 50 home runs in a season but topped 30 fifteen times and 40 eight times.\n\nAaron spent most of his 23-year career with the Milwaukee/Atlanta Braves, earning 25 All-Star selections (every year from 1955-1975) and winning the 1957 NL MVP. He remains the all-time leader in RBIs (2,297) and total bases (6,856).\n\nBreaking Babe Ruth's home run record in 1974, Aaron faced tremendous racial hatred and death threats, yet handled the pressure with dignity and grace. He was inducted into the Baseball Hall of Fame in 1982 with 97.8% of the vote and remains a symbol of excellence and perseverance in American sports.",

            'B Ruth' => "George Herman \"Babe\" Ruth is widely regarded as the greatest baseball player who ever lived. \"The Sultan of Swat\" revolutionized the game by transforming it from a low-scoring affair into a power-hitting spectacle. His 714 career home runs stood as the record for 39 years.\n\nRuth began his career as a dominant pitcher for the Boston Red Sox before being converted to an outfielder and sold to the New York Yankees in 1920—a transaction so infamous it spawned the \"Curse of the Bambino.\" With the Yankees, Ruth led the team to seven pennants and four World Series championships.\n\nHis 1927 season (60 home runs, 164 RBI, .356 average) is considered one of the greatest individual seasons in baseball history. Ruth's larger-than-life personality made him America's first true sports celebrity, and his impact on baseball remains unmatched. He was among the first five players inducted into the Baseball Hall of Fame in 1936.",

            'A Pujols' => "Albert Pujols is one of the most accomplished hitters of his generation, finishing his career with 703 home runs—fourth all-time in MLB history. His dominance in the 2000s with the St. Louis Cardinals was remarkable, winning three NL MVP awards and leading the Cardinals to two World Series championships.\n\nPujols was named to 11 All-Star teams and won two Gold Glove awards at first base. His first decade in the majors may be the greatest ever: he hit over .300 with at least 30 home runs and 100 RBI in each of his first ten seasons.\n\nAfter leaving St. Louis for the Los Angeles Angels in 2012, injuries slowed his production, but he remained a respected veteran presence. He finished his career back with the Cardinals in 2022, hitting his 700th home run in his final season and cementing his place as a first-ballot Hall of Famer.",

            'A Rodriguez' => "Alex Rodriguez, known as \"A-Rod,\" was one of the most talented and controversial players in baseball history. His 696 career home runs rank fourth all-time, and he won three AL MVP awards while earning 14 All-Star selections.\n\nRodriguez burst onto the scene as a 20-year-old shortstop with the Seattle Mariners, hitting .358 in 1996. He later signed the richest contract in sports history with the Texas Rangers before being traded to the New York Yankees, where he won his only World Series in 2009.\n\nHis career was marred by multiple performance-enhancing drug suspensions, including a season-long ban in 2014. Despite the controversies, Rodriguez's raw talent was undeniable—he's the only player to hit 30+ home runs in 15 different seasons and remains one of the greatest offensive shortstops/third basemen ever.",

            'W Mays' => "Willie Mays, \"The Say Hey Kid,\" is widely considered the most complete player in baseball history. His combination of power hitting, speed, defensive excellence, and baseball instincts was unmatched. He finished with 660 home runs, 3,283 hits, and 338 stolen bases.\n\nMays was a 24-time All-Star (every year from 1954-1973) and won two NL MVP awards while leading the New York/San Francisco Giants to a World Series title in 1954. His over-the-shoulder catch in that World Series remains one of the most iconic plays in baseball history.\n\nBeyond the statistics, Mays played with a joy and enthusiasm that captivated fans. His Hall of Fame induction in 1979 with 94.7% of the vote merely confirmed what everyone already knew—Willie Mays was one of the greatest to ever play the game.",

            'K Griffey' => "Ken Griffey Jr., \"The Kid,\" was the most popular player of his generation and possessed one of the sweetest swings in baseball history. His 630 career home runs rank seventh all-time, achieved despite numerous injuries that limited his later career.\n\nGriffey burst onto the scene with the Seattle Mariners at age 19, eventually winning the 1997 AL MVP and leading Seattle to multiple playoff appearances. He won 10 consecutive Gold Glove awards and was named to 13 All-Star teams.\n\nHis combination of power, defense, and charisma made him baseball's biggest star in the 1990s. Griffey was inducted into the Baseball Hall of Fame in 2016 with 99.32% of the vote—the highest percentage ever at that time—a testament to both his talent and his clean image during the steroid era.",

            'J Thome' => "Jim Thome was one of the most prolific left-handed power hitters in baseball history, clubbing 612 home runs over his 22-year career—eighth most all-time. Known for his towering home runs and humble demeanor, Thome was respected throughout baseball.\n\nThome spent his best years with the Cleveland Indians, where he helped lead the team to two World Series appearances in the 1990s. He later had productive stints with the Phillies, White Sox, and Twins.\n\nDespite never winning an MVP award, Thome was a five-time All-Star who drew over 1,700 walks, showing remarkable plate discipline for a power hitter. He was inducted into the Hall of Fame in 2018 with 89.8% of the vote.",

            'S Sosa' => "Sammy Sosa captivated baseball fans during the legendary 1998 home run chase with Mark McGwire, a race that helped revive baseball's popularity after the 1994 strike. Sosa finished with 609 career home runs, including an unprecedented three 60-homer seasons.\n\nPlaying primarily for the Chicago Cubs, Sosa was a seven-time All-Star and won the 1998 NL MVP award. His enthusiastic style of play, including his trademark hop after home runs, made him a fan favorite at Wrigley Field.\n\nSosa's legacy has been complicated by connections to performance-enhancing drugs, though he has never admitted to using them. He remains one of only nine players to hit 600 career home runs.",

            'F Robinson' => "Frank Robinson was the only player to win MVP awards in both leagues, earning the honor with the Cincinnati Reds in 1961 and the Baltimore Orioles in 1966. His 586 career home runs rank tenth all-time, and he was a fierce competitor known for crowding the plate.\n\nRobinson won two World Series with the Orioles and earned 14 All-Star selections. After his playing career, he became baseball's first African American manager with the Cleveland Indians in 1975.\n\nA first-ballot Hall of Famer inducted in 1982, Robinson's combination of power, leadership, and trailblazing made him one of the most important figures in baseball history.",

            'M McGwire' => "Mark McGwire's 70 home runs in 1998 broke Roger Maris's single-season record and, along with Sammy Sosa's pursuit, captivated the nation and helped restore baseball's popularity. He finished his career with 583 home runs despite playing only 16 seasons.\n\nMcGwire was a 12-time All-Star who won a World Series with the Oakland Athletics as part of the \"Bash Brothers\" duo with Jose Canseco. His massive home runs and tape-measure shots were legendary.\n\nHis admission of steroid use in 2010 tarnished his legacy and likely contributed to his failure to gain Hall of Fame induction during his time on the ballot.",

            'H Killebrew' => "Harmon Killebrew was one of the most feared power hitters of his era, smashing 573 home runs—primarily for the Minnesota Twins. His quiet demeanor off the field contrasted with his thunderous bat, which earned him 13 All-Star selections and the 1969 AL MVP award.\n\nKillebrew led the American League in home runs six times and drove in 100+ runs in nine seasons. Despite playing in an era of dominant pitching, he maintained exceptional power numbers throughout the 1960s.\n\nInducted into the Hall of Fame in 1984, Killebrew was known as one of the nicest players in baseball—a gentleman who happened to hit baseballs farther than almost anyone else.",

            'R Palmeiro' => "Rafael Palmeiro was one of the most consistent hitters of his era, accumulating 569 home runs and 3,020 hits over his 20-year career. He is one of only five players to reach both milestones, yet remains outside the Hall of Fame.\n\nPalmeiro won three Gold Glove awards at first base and was a four-time All-Star. He had his best years with the Texas Rangers and Baltimore Orioles.\n\nHis legacy was severely damaged when he tested positive for stanozolol in 2005, just months after emphatically denying steroid use before Congress. He has not come close to Hall of Fame induction.",

            'R Jackson' => "Reggie Jackson, \"Mr. October,\" earned his nickname with legendary postseason performances, including three consecutive home runs in Game 6 of the 1977 World Series. His 563 career home runs were accompanied by a flair for the dramatic unmatched in baseball history.\n\nJackson was a 14-time All-Star who won five World Series rings with the Oakland A's and New York Yankees. He led the league in home runs four times and won two World Series MVP awards.\n\nKnown for his confident personality and clutch hitting, Jackson was inducted into the Hall of Fame in 1993. His iconic status made him one of the first players to truly capitalize on his fame commercially.",

            'M Ramirez' => "Manny Ramirez was one of the greatest right-handed hitters in baseball history, finishing with 555 home runs and a .312 career batting average. His approach at the plate was studied for its mechanics, and he made hitting look effortless.\n\nRamirez was a 12-time All-Star who won two World Series championships with the Boston Red Sox, finally helping break the \"Curse of the Bambino\" in 2004. His quirky personality led to the phrase \"Manny being Manny.\"\n\nMultiple suspensions for performance-enhancing drugs have affected his Hall of Fame candidacy, but his hitting ability was undeniable—he drove in 100+ runs in 13 different seasons.",

            'M Schmidt' => "Mike Schmidt is widely considered the greatest third baseman in baseball history. His 548 home runs are the most ever by a player at that position, and he won three NL MVP awards while leading the Philadelphia Phillies to their first World Series championship in 1980.\n\nSchmidt was a 12-time All-Star who won 10 Gold Glove awards, proving he was as good with his glove as his bat. He led the NL in home runs eight times, more than any player except Babe Ruth.\n\nInducted into the Hall of Fame in 1995 with 96.5% of the vote, Schmidt's combination of power and defense at the hot corner set the standard for all future third basemen.",

            'D Ortiz' => "David \"Big Papi\" Ortiz transformed from a journeyman first baseman released by the Minnesota Twins into a Boston Red Sox legend and one of the greatest designated hitters ever. His 541 career home runs include countless clutch hits that defined an era of Red Sox baseball.\n\nOrtiz was the emotional leader of three World Series championship teams, helping end Boston's 86-year title drought in 2004. His Game 4 walk-off home run against the Yankees in that year's ALCS is one of the most iconic moments in baseball history.\n\nA 10-time All-Star, Ortiz retired as a beloved figure in Boston and was elected to the Hall of Fame in 2022 in his first year of eligibility.",

            'M Mantle' => "Mickey Mantle was a switch-hitting phenomenon who combined power, speed, and charisma to become one of baseball's greatest icons. His 536 home runs came despite playing his entire career with chronic knee injuries that limited what could have been.\n\nMantle won three AL MVP awards and led the New York Yankees to seven World Series championships. His 1956 Triple Crown season (.353, 52 HR, 130 RBI) was one of the most dominant individual years ever.\n\nInducted into the Hall of Fame in 1974, Mantle's ability to hit tape-measure home runs from both sides of the plate made him a legend. His battles with alcoholism later in life made him a cautionary tale, but his talent was transcendent.",

            'J Foxx' => "Jimmie Foxx, \"The Beast,\" was one of the most feared sluggers of the 1930s, hitting 534 career home runs with a .325 batting average. His massive forearms generated tremendous power, and he won three AL MVP awards.\n\nFoxx won the Triple Crown in 1933 and hit 30+ home runs in 12 consecutive seasons. He was a key player on the Philadelphia Athletics dynasty and later starred for the Boston Red Sox.\n\nInducted into the Hall of Fame in 1951, Foxx was considered the right-handed equivalent of Babe Ruth during his prime. His career was shortened by personal problems, but his peak was among the greatest ever.",

            'W McCovey' => "Willie McCovey, \"Stretch,\" terrorized National League pitchers with his towering home runs over an illustrious 22-year career. His 521 home runs were hit almost exclusively for the San Francisco Giants, where he formed a fearsome duo with Willie Mays.\n\nMcCovey won the 1969 NL MVP and was named to six All-Star teams. His left-handed power stroke was so feared that the cove beyond the right field wall at Oracle Park is named \"McCovey Cove\" in his honor.\n\nInducted into the Hall of Fame in 1986, McCovey was known for his friendly demeanor and remains one of the most beloved figures in Giants history.",

            'F Thomas' => "Frank Thomas, \"The Big Hurt,\" was one of the most complete hitters of his generation, combining power with exceptional plate discipline. His 521 career home runs were accompanied by a .419 career on-base percentage.\n\nThomas won back-to-back AL MVP awards in 1993-94 and was the first player to have seven consecutive seasons with a .300 average, 20+ home runs, 100+ RBI, and 100+ walks. He spent his best years with the Chicago White Sox.\n\nA five-time All-Star, Thomas was elected to the Hall of Fame in 2014 in his first year of eligibility. He was notably outspoken against performance-enhancing drugs throughout his career.",

            'T Williams' => "Ted Williams, \"The Splendid Splinter,\" is considered the greatest pure hitter in baseball history. His .344 career batting average and .482 on-base percentage speak to his exceptional eye, and he remains the last player to hit .400 in a season (.406 in 1941).\n\nWilliams' 521 home runs came despite losing nearly five prime seasons to military service in World War II and Korea, where he flew combat missions. He won two Triple Crowns and two AL MVP awards.\n\nInducted into the Hall of Fame in 1966, Williams' scientific approach to hitting revolutionized how the craft was taught. His book \"The Science of Hitting\" remains essential reading for hitters at all levels.",

            'E Banks' => "Ernie Banks, \"Mr. Cub,\" was the heart and soul of the Chicago Cubs for 19 seasons. His 512 career home runs and famous catchphrase \"Let's play two!\" made him one of baseball's most beloved figures despite never playing in a World Series.\n\nBanks won back-to-back NL MVP awards in 1958-59 as a shortstop, remarkable for a power hitter at that position. He was an 14-time All-Star who transitioned to first base later in his career.\n\nInducted into the Hall of Fame in 1977, Banks' sunny disposition and love for the game made him a Chicago icon. The Cubs retired his number 14, and a statue stands outside Wrigley Field.",

            'E Mathews' => "Eddie Mathews formed one of baseball's greatest home run duos with Hank Aaron, and his 512 career home runs were the most ever by a third baseman until Mike Schmidt broke his record. He was a nine-time All-Star known for his picture-perfect left-handed swing.\n\nMathews was a key player on the Milwaukee Braves teams that won consecutive pennants in 1957-58, including the 1957 World Series championship. He hit 30+ home runs in nine consecutive seasons.\n\nInducted into the Hall of Fame in 1978, Mathews' combination of power and defense made him one of the best third basemen of his era.",

            'M Ott' => "Mel Ott was one of the National League's first great power hitters, revolutionizing the game with his unique leg-kick batting stance. His 511 career home runs were a National League record for decades, and all were hit for the New York Giants.\n\nOtt was an 12-time All-Star who led the NL in home runs six times. He became player-manager of the Giants at just 33 years old.\n\nInducted into the Hall of Fame in 1951, Ott's career was remarkable for its longevity and consistency—he played 22 seasons, all with the same team.",

            'G Sheffield' => "Gary Sheffield's 509 career home runs came with one of the most intimidating batting stances in baseball history—his menacing bat waggle struck fear into pitchers. A nine-time All-Star, Sheffield played for eight teams over his 22-year career.\n\nSheffield's best seasons came with the Florida Marlins, Los Angeles Dodgers, and Atlanta Braves. He won a World Series with the Marlins in 1997 and finished in the top 10 in MVP voting six times.\n\nKnown for his fiery personality and ability to hit in the clutch, Sheffield remains one of the most productive hitters of his generation despite falling short of the Hall of Fame.",

            'M Cabrera' => "Miguel Cabrera is the most recent Triple Crown winner in baseball, accomplishing the feat in 2012 when he hit .330 with 44 home runs and 139 RBI. His combination of batting average and power has made him one of the best pure hitters of his generation.\n\nCabrera has won two AL MVP awards and was an 12-time All-Star. He reached 500 career home runs and 3,000 career hits, joining an exclusive club in baseball history.\n\nPlaying his entire career for the Florida Marlins and Detroit Tigers, Cabrera won a World Series with Florida in 2003. His Hall of Fame induction is assured when he becomes eligible.",

            'E Murray' => "Eddie Murray was the model of consistency, accumulating 504 home runs and 3,255 hits over his 21-year career. As a switch-hitter, he provided power from both sides of the plate while earning eight All-Star selections.\n\nMurray won three Gold Glove awards at first base and was the 1977 AL Rookie of the Year with the Baltimore Orioles. He won World Series championships with both Baltimore and Cleveland.\n\nInducted into the Hall of Fame in 2003, Murray was known for his quiet professionalism and ability to produce year after year. He drove in 75+ runs in 20 consecutive seasons.",

            'F McGriff' => "Fred McGriff, \"The Crime Dog,\" was one of the most consistent power hitters of his era, smashing 493 career home runs with a smooth left-handed swing. His ability to drive the ball to all fields made him a nightmare for pitchers.\n\nMcGriff was a five-time All-Star who hit 30+ home runs in ten different seasons. He helped the Braves win the 1995 World Series after a mid-season trade revitalized Atlanta's lineup.\n\nFinally inducted into the Hall of Fame in 2023 by the Contemporary Era Committee, McGriff's steady excellence was recognized after years of being overlooked on the regular ballot.",

            'D Kingman' => "Dave Kingman was one of baseball's most enigmatic players—capable of tape-measure home runs one moment and embarrassing strikeouts the next. His 442 career home runs came with a strikeout rate that foreshadowed modern hitters.\n\nKingman led the NL in home runs twice and hit 35+ homers six times. His 6'6\" frame generated tremendous power, but his contact skills were limited.\n\nHis confrontational relationship with the media and teammates made him a controversial figure, but his raw power was undeniable.",

            'J Giambi' => "Jason Giambi was one of the most feared hitters of the early 2000s, winning the 2000 AL MVP with the Oakland Athletics. His combination of power and plate discipline made him a .400 on-base percentage threat.\n\nGiambi was a five-time All-Star who hit 440 career home runs. His walks and slugging percentage made him one of the most productive hitters of his generation.\n\nHis 2007 apology for past \"mistakes\" without specifying PEDs reflected the complicated legacy of that era's power hitters.",

            'P Konerko' => "Paul Konerko was the heart of the Chicago White Sox for 16 seasons, captaining them to the 2005 World Series championship. His 439 career home runs came with quiet leadership and clutch hitting.\n\nKonerko was a six-time All-Star who hit a grand slam in the 2005 World Series. His consistent production and professionalism made him the face of the franchise.\n\nHis statue outside Guaranteed Rate Field honors his status as one of the most beloved White Sox players ever.",

            'A Dawson' => "Andre Dawson, \"The Hawk,\" was a five-tool player who won the 1987 NL MVP despite playing for the last-place Cubs. His 438 career home runs came with Gold Glove defense and base-stealing ability early in his career.\n\nDawson was an eight-time All-Star who won eight Gold Gloves in the outfield. His powerful arm and aggressive style made him a complete player.\n\nInducted into the Hall of Fame in 2010, Dawson's knees gave out from playing on artificial turf, but his peak years were spectacular.",

            'L Gehrig' => "Lou Gehrig, \"The Iron Horse,\" set a consecutive games played record of 2,130 that stood for 56 years. His 493 career home runs and .340 batting average rank among the greatest in history, cut short by the disease that now bears his name.\n\nGehrig's 1927 Yankees, alongside Babe Ruth, are considered the greatest team ever assembled. He won two AL MVP awards and drove in 100+ runs an astonishing 13 consecutive seasons.\n\nHis farewell speech at Yankee Stadium in 1939, declaring himself \"the luckiest man on the face of the earth\" despite his terminal diagnosis, remains one of sports' most poignant moments. He was inducted into the Hall of Fame that same year.",

            'S Musial' => "Stan Musial, \"Stan the Man,\" was the epitome of excellence and sportsmanship over his 22-year career with the St. Louis Cardinals. His 475 home runs and 3,630 hits made him one of the most complete hitters in baseball history.\n\nMusial won three NL MVP awards and seven batting titles while being named to 24 All-Star teams. His unique corkscrew batting stance produced remarkable consistency—he finished with exactly 1,815 hits at home and 1,815 on the road.\n\nInducted into the Hall of Fame in 1969, Musial was beloved for never being ejected from a game and for his genuine kindness. He remains the greatest Cardinal of all time.",

            'C Jones' => "Chipper Jones was the greatest switch-hitter of his generation and spent his entire 19-year career with the Atlanta Braves. His 468 home runs and .303 career batting average made him one of the best third basemen in history.\n\nJones won the 1999 NL MVP and was an eight-time All-Star. He was the cornerstone of the Braves dynasty that won 14 consecutive division titles and the 1995 World Series.\n\nInducted into the Hall of Fame in 2018 with 97.2% of the vote, Jones was known for his clutch hitting and for being the rare star who spent his entire career with one franchise.",

            'D Winfield' => "Dave Winfield's 465 career home runs came with a 6'6\" frame that made him one of the most imposing figures in baseball. A 12-time All-Star, Winfield was drafted by teams in four different sports—baseball, football, basketball, and hockey.\n\nWinfield had his best years with the San Diego Padres and New York Yankees, finally winning a World Series with Toronto in 1992. He was a seven-time Gold Glove winner with a cannon arm in right field.\n\nInducted into the Hall of Fame in 2001, Winfield's athletic ability and longevity made him one of the most complete players of his era.",

            'J Canseco' => "Jose Canseco was one of baseball's most dynamic players in the late 1980s, becoming the first player to hit 40 home runs and steal 40 bases in the same season. His 462 career home runs and muscular build made him a prototype for the modern power hitter.\n\nCanseco won the 1988 AL MVP and was a six-time All-Star. He and Mark McGwire formed the \"Bash Brothers\" on the Oakland Athletics, winning a World Series in 1989.\n\nHis 2005 book \"Juiced\" exposed widespread steroid use in baseball, including his own, making him a controversial but historically significant figure in the game.",

            'C Yastrzemski' => "Carl Yastrzemski, \"Yaz,\" is the only American League player to collect 3,000 hits and 400 home runs. His 1967 Triple Crown season led the Boston Red Sox to an improbable pennant in what became known as \"The Impossible Dream.\"\n\nYastrzemski was an 18-time All-Star who won seven Gold Glove awards in left field. His 23 seasons with the Red Sox are the most by any player with a single team in AL history.\n\nInducted into the Hall of Fame in 1989, Yaz was known for his intense work ethic and remarkable consistency over more than two decades.",

            'J Bench' => "Johnny Bench revolutionized the catcher position with his one-handed catching technique and powerful bat. His 389 home runs as a catcher remain the record for the position, and he anchored Cincinnati's \"Big Red Machine\" dynasty.\n\nBench won two NL MVP awards and was a 14-time All-Star who won 10 consecutive Gold Gloves. He was the World Series MVP in 1976 and helped Cincinnati win back-to-back championships.\n\nInducted into the Hall of Fame in 1989, Bench is universally considered the greatest catcher in baseball history.",

            'L Walker' => "Larry Walker was a five-tool player who won three batting titles and the 1997 NL MVP with the Colorado Rockies. His 383 career home runs were complemented by exceptional defense that earned him seven Gold Glove awards.\n\nWalker was a five-time All-Star who hit over .350 four times. Though some dismissed his numbers due to Coors Field's altitude, his road statistics were still excellent.\n\nInducted into the Hall of Fame in 2020, Walker was the second Canadian-born position player inducted and one of the most complete players of the 1990s.",

            'J DiMaggio' => "Joe DiMaggio, \"The Yankee Clipper,\" epitomized grace and excellence in everything he did. His 56-game hitting streak in 1941 is considered baseball's most unbreakable record, and his 361 home runs came with remarkable few strikeouts.\n\nDiMaggio won three AL MVP awards and nine World Series championships with the Yankees. His career was shortened by three years of military service during World War II.\n\nInducted into the Hall of Fame in 1955, DiMaggio's dignified presence made him an American icon. His marriage to Marilyn Monroe only added to his mystique.",

            'Y Berra' => "Yogi Berra won more World Series rings (10) than any player in history and was one of the best catchers ever to play. His 358 home runs were accompanied by legendary malapropisms that made him a beloved figure beyond baseball.\n\nBerra was an 18-time All-Star who won three AL MVP awards. His clutch hitting and ability to handle pitching staffs made him invaluable to the Yankees dynasty.\n\nInducted into the Hall of Fame in 1972, Berra's wisdom—\"It ain't over till it's over,\" \"When you come to a fork in the road, take it\"—transcended the sport.",

            'T Raines' => "Tim Raines was one of the greatest leadoff hitters in baseball history, stealing 808 bases with an astounding 84.7% success rate. His .385 on-base percentage and ability to disrupt games on the basepaths made him a nightmare for opponents.\n\nRaines was a seven-time All-Star who won the 1986 NL batting title. He spent his best years with the Montreal Expos before winning a World Series with the Yankees in 1996.\n\nInducted into the Hall of Fame in 2017, Raines was finally recognized as one of the elite players of the 1980s after years of being underrated.",

            'P Rose' => "Pete Rose, \"Charlie Hustle,\" is baseball's all-time hits leader with 4,256, a record many consider unbreakable. His relentless effort and headfirst slides embodied his nickname, and he played more games than anyone in history.\n\nRose was a 17-time All-Star who won three batting titles and three World Series rings. He was the 1973 NL MVP and could play almost any position on the field.\n\nDespite his on-field greatness, Rose was permanently banned from baseball in 1989 for gambling on games while managing the Cincinnati Reds. He remains ineligible for the Hall of Fame, making him one of baseball's most tragic figures.",

            'I Suzuki' => "Ichiro Suzuki was a hitting machine who combined contact skills, speed, and defense like no one else. His 3,089 MLB hits (plus 1,278 in Japan) and 10 consecutive 200-hit seasons set him apart as one of baseball's most unique talents.\n\nIchiro won the 2001 AL MVP and Rookie of the Year in the same season, collecting a then-record 242 hits. He was a 10-time All-Star who won 10 Gold Gloves for his exceptional right field defense.\n\nInducted into the Hall of Fame in 2025, Ichiro helped open the door for Japanese position players in MLB and brought an artistry to hitting that captivated fans worldwide.",

            'C Ripken Jr.' => "Cal Ripken Jr., \"The Iron Man,\" played in 2,632 consecutive games, shattering Lou Gehrig's record that had stood for 56 years. His 431 home runs as a shortstop redefined what was possible for the position.\n\nRipken won two AL MVP awards and was a 19-time All-Star. His streak ended in 1998, but not before he helped restore baseball's image after the 1994 strike with his consecutive games chase.\n\nInducted into the Hall of Fame in 2007 with 98.5% of the vote, Ripken is considered the greatest shortstop in American League history and a symbol of dedication and durability.",

            'M Piazza' => "Mike Piazza is widely regarded as the greatest hitting catcher in baseball history, with 427 career home runs—most ever by a player who was primarily a catcher. Amazingly, he was a 62nd-round draft pick who became a superstar.\n\nPiazza was a 12-time All-Star who finished in the top 10 in MVP voting nine times. His iconic post-9/11 home run for the Mets provided a cathartic moment for New York City.\n\nInducted into the Hall of Fame in 2016, Piazza proved that determination and talent could overcome any draft position.",

            'B Robinson' => "Brooks Robinson, \"The Human Vacuum Cleaner,\" is considered the greatest defensive third baseman in baseball history. His 16 Gold Glove awards remain a record for any position player, and his 1970 World Series performance is legendary.\n\nRobinson was an 18-time All-Star who won the 1964 AL MVP. He spent all 23 seasons with the Baltimore Orioles and was the heart of their championship teams.\n\nInducted into the Hall of Fame in 1983, Robinson's glove work set the standard for all future third basemen.",

            'C Fisk' => "Carlton Fisk's iconic walk-off home run in Game 6 of the 1975 World Series—with him waving it fair—is one of baseball's most memorable images. His 376 home runs as a catcher were a record until Mike Piazza broke it.\n\nFisk was an 11-time All-Star who played for both the Red Sox and White Sox. His durability behind the plate was remarkable, catching more games than anyone in history at the time.\n\nInducted into the Hall of Fame in 2000, Fisk chose to be inducted as a Red Sox despite playing more games with Chicago.",

            'R Kiner' => "Ralph Kiner led the National League in home runs his first seven seasons—a feat matched only by Babe Ruth. His 369 career home runs came despite a career shortened by back injuries, and he dominated the power category like few others.\n\nKiner was a six-time All-Star who hit 51 and 54 home runs in back-to-back seasons for the Pittsburgh Pirates. He later became a beloved broadcaster for the New York Mets for over 50 years.\n\nInducted into the Hall of Fame in 1975, Kiner was known for his wit and his famous quote: \"Home run hitters drive Cadillacs. Singles hitters drive Fords.\"",

            'V Guerrero' => "Vladimir Guerrero was a free-swinging phenom who could hit any pitch—literally anywhere—out of the park. His 449 career home runs and aggressive style made him one of the most exciting players of his generation.\n\nGuerrero won the 2004 AL MVP with the Angels and was a nine-time All-Star. He hit over .300 in 13 seasons and had one of the strongest outfield arms ever.\n\nInducted into the Hall of Fame in 2018, Guerrero's son Vladimir Jr. has continued the family legacy as one of baseball's brightest young stars.",

            'J Bagwell' => "Jeff Bagwell had one of the most distinctive batting stances in baseball—an extreme crouch that produced 449 home runs and a .297 average over 15 seasons, all with the Houston Astros.\n\nBagwell won the 1994 NL MVP unanimously and was a four-time All-Star. He and Craig Biggio formed the core of Astros teams that reached multiple playoffs.\n\nInducted into the Hall of Fame in 2017, Bagwell overcame unfounded PED suspicions to finally receive his deserved recognition.",

            'F Howard' => "Frank Howard, \"The Capital Punisher,\" stood 6'7\" and hit some of the longest home runs in baseball history. His 382 career home runs included prodigious shots that awed fans and players alike.\n\nHoward was a four-time All-Star who led the AL in home runs twice. He was the 1960 NL Rookie of the Year with the Dodgers before becoming a star in Washington.\n\nHis tape-measure home runs at RFK Stadium were so legendary that seats marking their landing spots were painted to commemorate them.",

            'T Helton' => "Todd Helton was the greatest first baseman in Colorado Rockies history, finishing with 369 home runs and a .316 career average. His 2000 season (.372 average, 147 RBI) was one of the greatest offensive years ever.\n\nHelton was a five-time All-Star who won three Gold Gloves. He spent all 17 seasons with the Rockies and remains their all-time leader in most offensive categories.\n\nHis Hall of Fame candidacy was complicated by Coors Field's effect on hitting statistics, but his road numbers were still excellent.",

            'A Kaline' => "Al Kaline, \"Mr. Tiger,\" played all 22 seasons for the Detroit Tigers, becoming one of the franchise's most beloved players. His 399 home runs and 3,007 hits made him an all-time great, and he won a World Series in 1968.\n\nKaline was an 18-time All-Star who won 10 Gold Gloves in right field. He became the youngest batting champion ever in 1955 at just 20 years old.\n\nInducted into the Hall of Fame in 1980, Kaline's grace and consistency made him a model for how to play the game.",

            'G Stanton' => "Giancarlo Stanton possesses some of the most prodigious raw power in baseball history, hitting tape-measure home runs with exit velocities that break records. His 59 home runs in 2017 were the most in the NL since 2001.\n\nStanton won the 2017 NL MVP and has been a four-time All-Star. His massive frame (6'6\", 245 lbs) generates bat speed that few can match.\n\nWhile injuries have limited his playing time, when healthy, Stanton is one of the most feared hitters in baseball.",

            'O Cepeda' => "Orlando Cepeda, \"The Baby Bull,\" won the 1967 NL MVP unanimously while leading the Cardinals to a World Series championship. His 379 career home runs were hit with a passion that made him a fan favorite everywhere he played.\n\nCepeda was a seven-time All-Star who won the 1958 NL Rookie of the Year. He played for both the Giants and Cardinals during their glory years.\n\nInducted into the Hall of Fame in 1999 by the Veterans Committee, Cepeda overcame personal struggles to receive his deserved recognition.",

            'J Kent' => "Jeff Kent was the most prolific home run-hitting second baseman in history, with 377 career round-trippers at the position. His gruff demeanor belied an intense competitiveness that drove him to excellence.\n\nKent won the 2000 NL MVP with the Giants and was a five-time All-Star. He drove in 90+ runs for 11 consecutive seasons.\n\nThough he fell short of the Hall of Fame on the ballot, Kent's offensive numbers from the second base position remain remarkable.",

            'W Stargell' => "Willie Stargell, \"Pops,\" was the heart and soul of the Pittsburgh Pirates for two decades. His 475 career home runs included some of the longest shots in Three Rivers Stadium history, and his leadership helped Pittsburgh win two World Series.\n\nStargell shared the 1979 NL MVP award and was the World Series MVP that year, leading the \"We Are Family\" Pirates to a championship at age 39. He was a seven-time All-Star known for awarding \"Stargell Stars\" to teammates.\n\nInducted into the Hall of Fame in 1988, Stargell's combination of power, leadership, and warmth made him one of the most beloved figures in Pirates history.",

            'C Delgado' => "Carlos Delgado was one of the most feared power hitters of his era, smashing 473 home runs over his 17-year career. Playing primarily for the Toronto Blue Jays, he was a two-time All-Star who drove in 100+ runs nine times.\n\nDelgado set a record by hitting four home runs in a single game in 2003. He was also known for his political activism, notably refusing to stand for \"God Bless America\" in protest of the Iraq War.\n\nThough he never won a World Series, Delgado's consistent production made him one of the best first basemen of the 2000s.",

            'A Dunn' => "Adam Dunn was the ultimate \"three true outcomes\" player—he either walked, struck out, or hit a home run. His 462 career homers came with a record-setting 2,379 strikeouts, but his power and patience made him a valuable contributor.\n\nDunn drew over 100 walks in eight seasons and hit 40+ home runs in four consecutive years. His swing-from-the-heels approach made every at-bat an adventure.\n\nWhile not a complete player, Dunn's commitment to his approach was unwavering, making him a fascinating figure in baseball analytics.",

            'N Cruz' => "Nelson Cruz defied aging curves by hitting more home runs after age 33 than before, finishing with over 460 career home runs. His late-career renaissance with the Orioles, Mariners, and Twins made him one of the most productive DHs in modern baseball.\n\nCruz was a seven-time All-Star who led the AL in home runs in 2014. His powerful right-handed stroke produced consistent 40-homer seasons well into his late 30s.\n\nHis longevity and late-career production made Cruz one of the most remarkable stories in recent baseball history.",

            'A Beltr?' => "Adrián Beltré was one of the greatest third basemen ever to play, combining elite defense with 477 career home runs. His 3,166 hits rank 16th all-time, and his playful personality made him a fan favorite everywhere he played.\n\nBeltré was a four-time All-Star and five-time Gold Glove winner. His hatred of having his head touched became a running joke that delighted teammates and fans.\n\nInducted into the Hall of Fame in 2024, Beltré's combination of production, defense, and charisma made him one of the most complete players of his generation.",

            'C Beltr?n' => "Carlos Beltrán was a five-tool player who excelled in the postseason, hitting 16 playoff home runs including a legendary 2004 NLCS against the Cardinals. His 435 career home runs and 312 stolen bases made him one of the most complete players of his era.\n\nBeltrán was a nine-time All-Star who won three Gold Gloves. He played for seven teams, bringing his professional approach wherever he went.\n\nHis career was tarnished by his role in the Houston Astros sign-stealing scandal, costing him a managerial job with the Mets before it began.",

            'J Gonzalez' => "Juan González was a two-time AL MVP known for his prodigious power and run production. His 434 career home runs came with a .561 slugging percentage, and he drove in 100+ runs in nine seasons.\n\nGonzález was a three-time All-Star who helped lead the Texas Rangers to their first playoff appearances. His 1998 season (45 HR, 157 RBI) was one of the most dominant offensive years of the decade.\n\nInjuries shortened what could have been a Hall of Fame career, but at his peak, few hitters were more dangerous.",

            'A Jones' => "Andruw Jones was arguably the greatest defensive center fielder in baseball history, winning 10 consecutive Gold Glove awards. His 434 career home runs from the center field position were remarkable, making him a true five-tool player.\n\nJones was a five-time All-Star who hit 51 home runs in 2005. His ability to track down fly balls in the gaps was unmatched, and his arm prevented countless baserunners from advancing.\n\nThough his career declined sharply after leaving Atlanta, his peak years were among the best ever for a center fielder.",

            'B Williams' => "Bernie Williams was the quiet cornerstone of the Yankees dynasty that won four World Series in five years. His 287 career home runs and switch-hitting ability made him one of the best center fielders of the 1990s.\n\nWilliams was a five-time All-Star and four-time Gold Glove winner. He won the 1998 AL batting title with a .339 average.\n\nA classically trained guitarist, Williams released jazz albums after retirement. His elegant style both on and off the field made him a beloved figure in Yankees history.",

            'E Encarnaci?n' => "Edwin Encarnación established himself as one of the most consistent power hitters of the 2010s, with 424 career home runs. His signature \"parrot walk\" home run trot became iconic during his time with the Toronto Blue Jays.\n\nEncarnación was a three-time All-Star who hit 30+ home runs in eight consecutive seasons. His walk-off home run in the 2016 AL Wild Card game remains one of the most memorable moments in Blue Jays history.\n\nHis ability to drive the ball to all fields made him a nightmare for pitchers throughout his career.",

            'D Evans' => "Dwight Evans, \"Dewey,\" was one of the most underrated players of his generation, combining power with elite defense in right field. His 385 career home runs and eight Gold Gloves made him a cornerstone of the Boston Red Sox for two decades.\n\nEvans was a three-time All-Star who led the AL in walks twice. His strong arm in right field at Fenway Park was legendary.\n\nThough he fell short of the Hall of Fame, analytics have revealed Evans to be far more valuable than traditional statistics suggested.",

            'A Soriano' => "Alfonso Soriano was a dynamic player who became only the fourth member of the 40-40 club (40 HR, 40 SB) in 2006. His 412 career home runs combined with 289 stolen bases made him one of baseball's most exciting players.\n\nSoriano was a seven-time All-Star who began his career as a second baseman before moving to the outfield. His powerful swing generated tremendous bat speed.\n\nHis free-swinging approach led to high strikeout totals, but when he connected, the ball traveled a long way.",

            'M Teixeira' => "Mark Teixeira was one of the premier switch-hitting power hitters of his era, smashing 409 career home runs from both sides of the plate. His combination of power and Gold Glove defense at first base made him highly valuable.\n\nTeixeira was a three-time All-Star who won five Gold Gloves. He helped lead the Yankees to the 2009 World Series championship.\n\nInjuries shortened his career, but at his best, few first basemen could match his all-around game.",

            'D Snider' => "Duke Snider, \"The Silver Fox,\" was the center fielder for the Brooklyn Dodgers \"Boys of Summer\" teams. His 407 career home runs made him one of the three legendary New York center fielders of the 1950s, alongside Willie Mays and Mickey Mantle.\n\nSnider hit 40+ home runs five consecutive seasons and drove in 130+ runs four times. He helped the Dodgers win their only Brooklyn championship in 1955.\n\nInducted into the Hall of Fame in 1980, Snider represented the golden age of baseball in New York.",

            'A Galarraga' => "Andres Galarraga, \"The Big Cat,\" combined grace at first base with prodigious power, hitting 399 career home runs. His 1996 season with Colorado (.304, 47 HR, 150 RBI) was remarkable even for Coors Field.\n\nGalarraga was a five-time All-Star who won two Gold Gloves and two batting titles. His comeback from cancer in 2000 was one of baseball's most inspiring stories.\n\nHis smooth defensive work at first base belied his 6'3\", 235-pound frame, earning him his feline nickname.",

            'D Murphy' => "Dale Murphy was the face of the Atlanta Braves in the 1980s, winning back-to-back NL MVP awards in 1982-83. His 398 career home runs and seven consecutive All-Star appearances made him one of the decade's best players.\n\nMurphy won five Gold Gloves in center field and four Silver Slugger awards. He was known for his clean-cut image and charitable work.\n\nThough he fell short of the Hall of Fame, Murphy remains one of the most beloved players in Braves history.",

            'J Carter' => "Joe Carter will forever be remembered for his walk-off home run in Game 6 of the 1993 World Series—only the second Series-ending homer in history. His 396 career home runs came with a flair for dramatic moments.\n\nCarter was a five-time All-Star who drove in 100+ runs 10 times. He was a key player on two Blue Jays championship teams.\n\nHis iconic moment, jumping around the bases after touching the plate, remains one of baseball's most replayed highlights.",

            'J Edmonds' => "Jim Edmonds combined elite defense with power hitting, making spectacular diving catches look routine while belting 393 career home runs. His acrobatic catches in center field earned him eight Gold Glove awards.\n\nEdmonds was a four-time All-Star who helped lead the Cardinals to a World Series championship in 2006. His walk-off home run in Game 6 of the 2004 NLCS was legendary.\n\nHis ability to impact games with both his bat and glove made him one of the most complete center fielders of his era.",

            'G Nettles' => "Graig Nettles was the premier defensive third baseman of the 1970s, making spectacular plays look routine while hitting 390 career home runs. His 1978 World Series performance, robbing multiple hits with diving catches, was legendary.\n\nNettles was a six-time All-Star who won two Gold Gloves. He helped the Yankees win two World Series championships.\n\nHis dry wit and defensive brilliance made him a fan favorite in New York during the Bronx Zoo era.",

            'A Ramirez' => "Aramis Ramirez was a model of consistency at third base, hitting 386 career home runs while driving in 100+ runs four times. His smooth swing produced power to all fields.\n\nRamirez was a three-time All-Star who spent his best years with the Chicago Cubs. His clutch hitting in big moments made him a fan favorite at Wrigley Field.\n\nQuiet and professional, Ramirez let his bat do the talking throughout his 18-year career.",

            'H Baines' => "Harold Baines was the epitome of a professional hitter, accumulating 384 career home runs over 22 seasons with his compact, line-drive swing. His smooth approach made him one of the most consistent designated hitters in AL history.\n\nBaines was a six-time All-Star whose best years came with the Chicago White Sox. He drove in 90+ runs seven times with minimal fanfare.\n\nHis 2019 Hall of Fame induction was controversial due to his low profile, but those who watched him play appreciated his quiet excellence.",

            'R Howard' => "Ryan Howard burst onto the scene by winning both the NL Rookie of the Year and MVP in consecutive seasons (2005-06). His 382 career home runs came with a powerful left-handed swing that terrorized pitchers.\n\nHoward's 58 home runs in 2006 set a record for second-year players. He helped lead the Phillies to the 2008 World Series championship.\n\nAchilles injuries derailed his career prematurely, but at his peak, few hitters generated more fear than the \"Big Piece.\"",

            'J Rice' => "Jim Rice was one of the most feared hitters of the late 1970s and 1980s, winning the 1978 AL MVP with a .315 average, 46 home runs, and 139 RBI. His 382 career home runs came with intimidating intensity.\n\nRice was an eight-time All-Star who led the AL in home runs three times. His powerful left-handed stroke was perfectly suited for Fenway Park.\n\nInducted into the Hall of Fame in 2009, Rice was the most dominant hitter in the American League during his prime years.",

            'A Belle' => "Albert Belle was one of the most feared—and most volatile—hitters of the 1990s. His 381 career home runs and five consecutive 100-RBI seasons made him one of the decade's most productive players.\n\nBelle was a five-time All-Star who hit .317 with 50 home runs and 52 doubles in 1995—the only 50-50 season in history. His corked bat incident and confrontational nature made headlines.\n\nHip injuries ended his career abruptly, but at his best, Belle was among the game's most dangerous hitters.",

            'G Hodges' => "Gil Hodges was the powerful first baseman for the Brooklyn Dodgers dynasty, hitting 370 career home runs while driving in 100+ runs seven consecutive seasons. His fielding excellence made him one of the best defensive first basemen of his era.\n\nHodges was an eight-time All-Star who later managed the 1969 \"Miracle Mets\" to a stunning World Series championship.\n\nThough still awaiting Hall of Fame induction during his lifetime, Hodges was finally inducted in 2022, decades after his 1972 death.",

            'A Perez' => "Tony Pérez, \"Big Dog,\" was the RBI machine for Cincinnati's \"Big Red Machine,\" driving in 100+ runs seven times. His 379 career home runs and clutch hitting made him indispensable to one of baseball's greatest teams.\n\nPérez was a seven-time All-Star who won two World Series with the Reds. His leadership in the clubhouse was as valuable as his bat.\n\nInducted into the Hall of Fame in 2000, Pérez was the heart of the Big Red Machine's lineup.",

            'M Williams' => "Matt Williams was a power-hitting third baseman who was on pace to break Roger Maris's home run record before the 1994 strike ended his season at 43 home runs. His 378 career homers came with excellent defense.\n\nWilliams was a five-time All-Star and four-time Gold Glove winner. He drove in 100+ runs four times in a five-year span.\n\nThe strike robbed him of a chance at history, but Williams remained one of the best all-around third basemen of his era.",

            'N Cash' => "Norm Cash won the 1961 AL batting title with an astronomical .361 average, though his career .271 average suggests that season was an outlier. His 377 career home runs made him a key part of the Tigers' 1968 championship team.\n\nCash was a five-time All-Star whose left-handed power stroke was well-suited for Tiger Stadium. His sense of humor made him a fan favorite.\n\nHe once came to bat against Nolan Ryan with a table leg, knowing he had no chance of making contact.",

            'R Colavito' => "Rocky Colavito was one of baseball's most popular players in the late 1950s and early 1960s, hitting 374 career home runs with movie-star looks. His trade from Cleveland sparked outrage among Indians fans.\n\nColavito was a nine-time All-Star who led the AL in RBI in 1965. He hit four home runs in a game in 1959, becoming only the third AL player to accomplish the feat.\n\nHis popularity with fans rivaled any player of his era, and his departure from Cleveland remained a sore point for decades.",

            'L Berkman' => "Lance Berkman, \"The Big Puma,\" was a switch-hitting force who combined power with exceptional plate discipline. His 366 career home runs came with a .406 career on-base percentage.\n\nBerkman was a six-time All-Star who helped the Astros reach their first World Series in 2005. His 2011 comeback with the Cardinals, winning a World Series, was remarkable.\n\nHis combination of power from both sides and keen batting eye made him one of the best all-around hitters of his generation.",

            'G Gaetti' => "Gary Gaetti was a steady third baseman who hit 360 career home runs over 20 seasons. His power and solid defense made him a valuable contributor for multiple teams.\n\nGaetti was a two-time All-Star and four-time Gold Glove winner. He was the 1987 ALCS MVP for the Twins' championship team.\n\nQuiet and consistent, Gaetti exemplified the professional approach throughout his long career.",

            'J Mize' => "Johnny Mize, \"The Big Cat,\" was one of the most feared sluggers of the 1930s and 1940s, hitting 359 home runs while batting .312 for his career. He led the league in home runs four times despite losing three prime years to World War II.\n\nMize was a ten-time All-Star who won four World Series rings with the Yankees at the end of his career. He hit three home runs in a game a record six times.\n\nInducted into the Hall of Fame in 1981, Mize's combination of power and contact hitting was exceptional.",

            'C Lee' => "Carlos Lee, \"El Caballo,\" was a consistent run producer who hit 358 career home runs while driving in 100+ runs five times. His stocky build and aggressive approach made him a reliable middle-of-the-order hitter.\n\nLee was a three-time All-Star who played for six teams over his 14-year career. His best seasons came with the White Sox and Brewers.\n\nThough never flashy, Lee's steady production made him valuable to every team he played for.",

            'G Vaughn' => "Greg Vaughn overcame injuries and a trade to find his power stroke, hitting 355 career home runs including a career-high 50 in 1998. His resurgence with the Padres made him one of baseball's best stories.\n\nVaughn was a four-time All-Star who helped the Padres reach the 1998 World Series. He hit 40+ home runs three times in his career.\n\nHis perseverance through early career struggles made his later success all the more satisfying.",

            'L Gonzalez' => "Luis Gonzalez will forever be remembered for his walk-off single against Mariano Rivera in Game 7 of the 2001 World Series. His 354 career home runs included a shocking 57-homer season that same year.\n\nGonzalez was a five-time All-Star who became the heart of the Diamondbacks' franchise. His dramatic World Series hit ended one of the greatest Fall Classics ever.\n\nHis unlikely power surge in his 30s made him one of baseball's most improbable stars.",

            'L May' => "Lee May was a powerful first baseman who hit 354 career home runs as a key member of the Big Red Machine before being traded for Joe Morgan. His 39 home runs in 1969 helped Cincinnati reach the playoffs.\n\nMay was a three-time All-Star who drove in 100+ runs four times. His consistent power made him a valuable run producer.\n\nOften overlooked on the star-studded Reds teams, May's contributions were essential to their success.",

            'T Hunter' => "Torii Hunter was a rare combination of elite defense and solid power, winning nine Gold Glove awards while hitting 353 career home runs. His leaping catches at the wall were his trademark.\n\nHunter was a five-time All-Star who was beloved in every clubhouse for his leadership and enthusiasm. His smile and energy were infectious.\n\nHis ability to impact games with both his bat and glove made him one of the most complete center fielders of the 2000s.",

            'R Braun' => "Ryan Braun won the 2007 NL Rookie of the Year and 2011 NL MVP, hitting 352 career home runs for the Milwaukee Brewers. His quick swing generated tremendous bat speed and power.\n\nBraun was a six-time All-Star who helped the Brewers reach the playoffs multiple times. He combined power with a .296 career batting average.\n\nHis legacy was complicated by a PED suspension in 2013, but his on-field production was undeniable.",

            'H Matsui' => "Hideki Matsui, \"Godzilla,\" brought his legendary status from Japan to America, hitting 175 MLB home runs (507 combined with NPB). His 2009 World Series MVP performance, going 8-for-13 with 3 home runs, was historic.\n\nMatsui was a two-time All-Star who was beloved by Yankees fans for his clutch hitting and professional approach.\n\nHis excellence in the World Series cemented his legacy as one of the greatest Japanese players to play in MLB.",

            'B Belt' => "Brandon Belt was the heart of the San Francisco Giants' championship core, winning three World Series rings while developing into a patient, powerful first baseman. His 175+ career home runs came with excellent on-base skills.\n\nBelt's ability to work counts and draw walks made him valuable despite injuries limiting his playing time. His quirky personality made him a fan favorite.\n\nHis contributions to three championships ensured his place in Giants history.",

            'T Story' => "Trevor Story established himself as one of baseball's premier power-hitting shortstops, setting rookie records for home runs at the position. His combination of power and speed made him a dynamic player.\n\nStory was a two-time All-Star who hit 30+ home runs three times. His ability to impact games with his bat and athleticism was remarkable.\n\nHis transition to other positions later showed his versatility and team-first attitude.",

            'C Yelich' => "Christian Yelich transformed into an MVP-caliber player with the Brewers, winning back-to-back batting titles in 2018-19 while combining power and speed. His 2018 NL MVP season (.326, 36 HR, 110 RBI) announced his arrival as a superstar.\n\nYelich is a three-time All-Star whose smooth left-handed swing produces line drives to all fields.\n\nInjuries have slowed his recent production, but at his best, Yelich is one of baseball's most complete hitters.",

            'R Odor' => "Rougned Odor brought intensity and power to the second base position, hitting memorable home runs while playing with fire. He became famous for punching José Bautista in a 2016 brawl.\n\nOdor's 30-homer season in 2016 showed his power potential. His aggressive approach led to strikeouts but also spectacular moments.\n\nHis fiery personality made him a polarizing but entertaining figure in baseball.",

            'B Buckner' => "Bill Buckner was a consistent hitter who collected 2,715 career hits and won the 1980 NL batting title. Despite his productive career, he's unfortunately remembered most for an error in the 1986 World Series.\n\nBuckner was an All-Star who hit .289 over 22 seasons, playing through chronic ankle injuries with remarkable determination.\n\nHis long career of excellence deserves to be remembered alongside that one fateful moment.",

            'J Schoop' => "Jonathan Schoop emerged as a power-hitting second baseman, smashing 32 home runs in 2017 while providing solid defense. His ability to drive the ball with authority from the right side made him valuable.\n\nSchoop was an All-Star who brought energy and enthusiasm to the field. His raw power from the second base position was impressive.\n\nHis contributions to winning teams showed his value as a middle infielder with pop.",

            'J Franco' => "Julio Franco had one of baseball's longest careers, playing until age 48 while accumulating over 2,500 hits. His unique batting stance—bat held high and waggling—was instantly recognizable.\n\nFranco won the 1991 AL batting title and was a three-time All-Star. His ability to make contact remained elite throughout his career.\n\nHis longevity was remarkable, proving that dedication and proper conditioning could extend a career well beyond normal limits.",

            'W Cooper' => "Walker Cooper was one of the premier catchers of the 1940s, combining power with solid defense behind the plate. His 173 career home runs came in an era when catchers rarely hit for power.\n\nCooper was an eight-time All-Star who helped the Cardinals win multiple World Series. His partnership with brother Mort formed a legendary battery.\n\nHis selection to multiple All-Star teams demonstrated his standing among the best catchers of his era.",

            'K Calhoun' => "Kole Calhoun was a hard-nosed outfielder who provided solid power and excellent defense for the Angels. His hustle and competitiveness made him a clubhouse favorite.\n\nCalhoun's ability to play all three outfield positions while contributing with his bat made him valuable. His strong arm prevented runners from taking extra bases.\n\nHis gritty style of play exemplified the team-first attitude that managers value.",

            'M Grace' => "Mark Grace was a contact-hitting machine who led the majors in hits during the 1990s. His 173 career home runs weren't spectacular, but his .303 career average and 2,445 hits were.\n\nGrace was a three-time All-Star and four-time Gold Glove winner at first base. His smooth left-handed swing consistently sprayed line drives.\n\nHis contributions to the Cubs' 1989 playoff run and later the Diamondbacks' 2001 championship made him a winner at both ends of his career.",

            'N Colbert' => "Nate Colbert was the first star in San Diego Padres history, hitting 163 home runs in just five seasons with the team. His 1972 season (38 HR, 111 RBI) remains one of the best in franchise history.\n\nColbert hit five home runs and drove in 13 runs in a doubleheader in 1972, setting records that still stand. He was a two-time All-Star.\n\nInjuries shortened his career, but Colbert remains a foundational figure in Padres history.",

            'J Pederson' => "Joc Pederson earned a reputation as a postseason hero, providing clutch power for multiple championship teams. His left-handed power and October magic made him valuable.\n\nPederson was an All-Star who hit key home runs for the Dodgers and Braves in the playoffs. His confident personality matched his big-game production.\n\nHis ability to deliver in pressure moments defined his career more than regular season statistics.",

            'E Robinson' => "Eddie Robinson was a solid first baseman who played for seven teams over 13 seasons, hitting 172 career home runs. He was an All-Star in 1949 and 1951.\n\nRobinson had his best seasons with the Indians and White Sox, providing steady production at first base.\n\nHis long executive career after playing, including serving as Rangers GM, extended his impact on baseball.",

            'M Vernon' => "Mickey Vernon won two AL batting titles while playing stellar defense at first base. His 172 career home runs were secondary to his ability to spray line drives and play Gold Glove-caliber defense.\n\nVernon was a seven-time All-Star who played 20 seasons in the majors. His smooth left-handed swing was a model of efficiency.\n\nHis longevity and consistency made him one of the most respected players of his generation.",

            'K Bryant' => "Kris Bryant was the NL MVP in 2016 while leading the Cubs to their first World Series championship in 108 years. His combination of power and athleticism made him one of baseball's brightest young stars.\n\nBryant was a four-time All-Star who hit 26 home runs as a rookie in 2015. His versatility allowed him to play multiple positions.\n\nInjuries have slowed his career, but his role in ending the Cubs' championship drought ensures his place in baseball history.",

            'M Mora' => "Melvin Mora was a versatile player who found stardom late, making his first All-Star team at age 32. His 171 career home runs and ability to play multiple positions made him valuable.\n\nMora finished fourth in the 2004 AL MVP voting after hitting .340 with 27 home runs for the Orioles. He played nearly every position on the field during his career.\n\nHis journey from journeyman to All-Star was one of baseball's best late-bloomer stories.",

            'R Hidalgo' => "Richard Hidalgo showed tremendous power potential, hitting 44 home runs in 2000 to establish himself as one of baseball's rising stars. His 169 career home runs suggested what might have been without injuries.\n\nHidalgo was an All-Star whose right-handed power and strong arm in right field made him a complete player.\n\nInjuries derailed a promising career, but his peak seasons showed elite potential.",

            'D Young' => "Dmitri Young, \"Da Meat Hook,\" was a switch-hitting first baseman and designated hitter who became an unlikely All-Star late in his career. He hit three home runs on Opening Day 2005.\n\nYoung overcame personal struggles to have a remarkable 2007 season with the Nationals, making his only All-Star team.\n\nHis perseverance through difficulties showed the human side of professional baseball.",

            'J Cronin' => "Joe Cronin was a Hall of Fame shortstop who became one of the best managers and executives in baseball history. His 170 career home runs were impressive for a shortstop in the 1930s.\n\nCronin was a seven-time All-Star and player-manager who led the Red Sox for many years. He later served as AL President.\n\nInducted into the Hall of Fame in 1956, Cronin's impact on baseball extended far beyond his playing days.",

            'K Millar' => "Kevin Millar was the heart and soul of the 2004 Red Sox, coining the phrase \"Cowboy Up\" and helping end the Curse of the Bambino. His 170 career home runs were secondary to his clubhouse presence.\n\nMillar's personality and leadership were invaluable to the championship run. He later became a popular MLB Network analyst.\n\nHis contributions to baseball history went beyond statistics to the intangibles that create championship teams.",

            'M Carpenter' => "Matt Carpenter transformed himself into one of baseball's best leadoff hitters, leading the NL in hits, doubles, and runs in various seasons. His patience and power made him a unique table-setter.\n\nCarpenter was a three-time All-Star whose left-handed swing was grooved for doubles. His 2018 season (36 HR) showed new power potential.\n\nHis dedication to adjusting his approach throughout his career demonstrated his baseball intelligence.",

            'B Elliott' => "Bob Elliott was a power-hitting third baseman who won the 1947 NL MVP with the Braves. His 170 career home runs came with a high batting average and solid defense.\n\nElliott was a seven-time All-Star who drove in 100+ runs four times. He helped the Braves reach the 1948 World Series.\n\nHis MVP season remains a highlight in Braves franchise history.",

            'J Hart' => "John Hart the player had a brief major league career, but his namesake executive transformed the Cleveland Indians into a powerhouse in the 1990s, building teams that reached two World Series.\n\nThe player John Hart contributed during his time in the majors before injuries limited his career.\n\nHis contributions, though brief, were part of the game's fabric.",

            'E Slaughter' => "Enos Slaughter's \"Mad Dash\" in the 1946 World Series—scoring from first on a single—remains one of baseball's most iconic moments. His 169 career home runs came with a .300 batting average and legendary hustle.\n\nSlaughter was a ten-time All-Star who always gave maximum effort. He played until age 43, running out every ground ball.\n\nInducted into the Hall of Fame in 1985, Slaughter epitomized playing the game the right way.",

            'R Hernandez' => "Ramón Hernández was a steady presence behind the plate who hit 161 career home runs while catching for several teams. His leadership and handling of pitching staffs made him valuable.\n\nHernández was a two-time All-Star who provided consistent offense from the catcher position.\n\nHis durability and professionalism made him a respected veteran throughout his career.",

            'L Moseby' => "Lloyd Moseby was the center fielder for the Blue Jays' rise to contention in the 1980s. His 169 career home runs combined with speed and defense made him one of the AL's best all-around players.\n\nMoseby was a two-time All-Star who formed a dynamic outfield with Jesse Barfield and George Bell.\n\nHis contributions helped establish the Blue Jays as a legitimate franchise.",

            'T Wigginton' => "Ty Wigginton was the definition of a journeyman, playing for eight teams while providing versatile bench production. His 165 career home runs came while playing multiple positions.\n\nWigginton's ability to fill in anywhere on the diamond made him valuable to roster construction.\n\nHis 24-homer season in 2010 showed he could still produce when given regular playing time.",

            'P O\'Brien' => "Pete O'Brien was a steady first baseman who hit 169 career home runs while providing solid defense. His consistency made him a reliable contributor for the Rangers and Indians.\n\nO'Brien had his best seasons in Texas, hitting 20+ home runs three times.\n\nHis professionalism and steady production made him a valued teammate.",

            'A Rios' => "Alex Rios was a talented outfielder whose tools never quite translated into superstardom. His 169 career home runs came with speed and defensive ability.\n\nRios was a two-time All-Star who showed flashes of brilliance but struggled with consistency.\n\nHis combination of skills made him tantalizing, even if he never reached his full potential.",

            'J Hernandez' => "José Hernández set an unusual record by striking out 188 times in 2002, but his 167 career home runs showed legitimate power. His defense at shortstop was valuable.\n\nHernández hit 24+ home runs three times, showing pop unusual for a middle infielder.\n\nHis willingness to swing made him prone to strikeouts but also produced exciting power.",

            'G Triandos' => "Gus Triandos was one of the best power-hitting catchers of the 1950s, hitting 167 career home runs. His 30-homer season in 1958 was remarkable for a catcher in that era.\n\nTriandos was a four-time All-Star who caught Hoyt Wilhelm's knuckleball despite its difficulty.\n\nHis power from behind the plate made him an offensive threat at a traditionally weak hitting position.",

            'B Zobrist' => "Ben Zobrist was the ultimate super-utility player, providing clutch hitting and versatility to championship teams. His World Series MVP in 2016 for the Cubs was the highlight of a remarkable career.\n\nZobrist was a three-time All-Star who played every position except pitcher and catcher. His \"Zorilla\" nickname reflected his fan popularity.\n\nHis leadership and flexibility made him invaluable to the Rays, Royals, and Cubs championship cultures.",

            'C Blake' => "Casey Blake was a reliable third baseman who hit 162 career home runs while playing for several teams. His steady production and solid defense made him a valuable contributor.\n\nBlake had his best seasons with the Indians, hitting 20+ home runs three times.\n\nHis professional approach and consistency made him a respected veteran.",

            'C Johnson' => "Charles Johnson was one of the premier defensive catchers of the 1990s, winning four Gold Gloves while contributing 167 career home runs. His defense was elite.\n\nJohnson was a two-time All-Star whose receiving skills and arm strength made him invaluable.\n\nHis ability to control the running game was legendary among pitchers who threw to him.",

            'E Howard' => "Elston Howard broke barriers as the first Black player on the Yankees, winning the 1963 AL MVP while catching championship teams. His 167 career home runs came with Gold Glove defense.\n\nHoward was a nine-time All-Star who won four World Series rings. His dignity and excellence paved the way for future generations.\n\nInducted into the Yankees' Monument Park, Howard's legacy transcends statistics.",

            'P Sorrento' => "Paul Sorrento was a power-hitting first baseman who hit 166 career home runs with a sweet left-handed swing. His 25-homer seasons showed legitimate power.\n\nSorrento had his best years with Cleveland, contributing to their 1990s success.\n\nHis friendly personality and consistent production made him a valued teammate.",

            'T Conigliaro' => "Tony Conigliaro was on track for superstardom before a horrific beaning in 1967 damaged his eyesight. His 166 career home runs by age 22 suggested a potential Hall of Fame career.\n\nConigliaro was the youngest player to reach 100 home runs in AL history. His comeback attempts showed tremendous courage.\n\nHis story remains one of baseball's great tragedies—a career cut short by circumstances beyond his control.",

            'J B?ez' => "Javy Báez, \"El Mago,\" is one of baseball's most exciting players, combining elite defense with dramatic swings. His magical tag plays and aggressive style make every game entertaining.\n\nBáez was a two-time All-Star and World Series champion with the Cubs in 2016. His willingness to swing at any pitch creates spectacular moments.\n\nHis style of play—all-or-nothing at the plate, wizardry in the field—makes him unique in modern baseball.",

            'C Rasmus' => "Colby Rasmus was a toolsy center fielder whose potential was never fully realized. His combination of power and defense suggested stardom that didn't materialize consistently.\n\nRasmus hit 28 home runs in 2015 for the Astros, showing his ceiling.\n\nInjuries and inconsistency limited what could have been a more productive career.",

            'L Hisle' => "Larry Hisle was an All-Star outfielder whose career was derailed by shoulder injuries. His 166 career home runs included a monster 1977 season (28 HR, 119 RBI) for the Twins.\n\nHisle's combination of power and run production made him one of baseball's best before injuries struck.\n\nHis story is one of potential unfulfilled due to circumstances beyond his control.",

            'Y Cespedes' => "Yoenis Céspedes brought Cuban flair to MLB, displaying prodigious power and a cannon arm. His 162 career home runs included dramatic moments for the Athletics and Mets.\n\nCéspedes was a two-time All-Star whose outfield arm was legendary. He helped carry the Mets to the 2015 World Series.\n\nInjuries limited his later career, but his impact when healthy was electrifying.",

            'J Cruz' => "José Cruz Sr. was a consistently productive outfielder who hit 165 career home runs while batting .284 over 19 seasons. His best years came with the Houston Astros.\n\nCruz was a two-time All-Star who combined solid power with excellent contact skills.\n\nHis long career of steady production made him a valued contributor for multiple teams.",

            'J Jones' => "Jacque Jones was a solid outfielder who hit 165 career home runs while providing steady defense. His best seasons came with the Minnesota Twins.\n\nJones had back-to-back 20-homer seasons and contributed to winning teams.\n\nHis professional approach made him a reliable contributor throughout his career.",

            'A Duvall' => "Adam Duvall emerged as a legitimate power threat, hitting 40 home runs in 2016 after being a minor league afterthought. His pull power to left field was exceptional.\n\nDuvall's aggressive approach made him streaky but dangerous when hot.\n\nHis story of perseverance and late development inspired many who had been overlooked.",

            'A Van Slyke' => "Andy Van Slyke was a three-time All-Star who combined power, speed, and Gold Glove defense. His 164 career home runs came with style and flair.\n\nVan Slyke won five Gold Gloves in center field while providing consistent offense. His wit made him a media favorite.\n\nHis all-around game made him one of the best center fielders of the late 1980s.",

            'C Hafey' => "Chick Hafey won the 1931 NL batting title despite severe eyesight problems. His 164 career home runs came while he often couldn't clearly see the pitcher.\n\nHafey was a Hall of Famer whose determination overcame significant physical limitations.\n\nInducted in 1971, Hafey's story of perseverance remains inspiring.",

            'J Turner' => "Justin Turner transformed himself from journeyman to All-Star with the Dodgers, becoming a clutch postseason performer. His 162 career home runs included key playoff moments.\n\nTurner made three All-Star teams and helped the Dodgers win the 2020 World Series.\n\nHis late-career success story showed that patience and opportunity can change everything.",

            'J Lemon' => "Jim Lemon was a power hitter who led the AL in strikeouts three times but also hit 164 career home runs. His 38-homer season in 1956 showed his raw power.\n\nLemon was an All-Star whose swing-from-the-heels approach was ahead of its time.\n\nHis career showed the power-strikeout tradeoff that defines many modern hitters.",

            'C Washington' => "Claudell Washington had all the tools but never quite put it all together over his 17-year career. His 164 career home runs and speed suggested superstar potential.\n\nWashington was a two-time All-Star who hit for the cycle twice.\n\nHis story is one of talent that fell short of its considerable ceiling.",

            'H Bauer' => "Hank Bauer was a hard-nosed outfielder who won seven World Series rings with the Yankees. His 164 career home runs came with fierce competitiveness.\n\nBauer was a two-time All-Star whose intensity helped define the championship culture in New York.\n\nHis later success as manager of the 1966 Orioles showed his leadership abilities.",

            'B Upton' => "B.J. Upton (now Melvin) was a talented but inconsistent center fielder whose tools never translated into consistent production. His combination of power and speed was tantalizing.\n\nUpton had his best seasons with Tampa Bay, helping them reach the 2008 World Series.\n\nHis career showed that raw talent doesn't always guarantee stardom.",

            'A Smith' => "Al Smith was a steady outfielder who hit 164 career home runs while providing solid defense. He was a two-time All-Star in the 1950s and 1960s.\n\nSmith helped the White Sox reach the 1959 World Series with his consistent contributions.\n\nHis long career of solid production made him a valued contributor.",

            'A Seminick' => "Andy Seminick was a power-hitting catcher who hit 164 career home runs in an era when catchers rarely hit for power. He was a two-time All-Star.\n\nSeminick's power from behind the plate was ahead of his time.\n\nHis contributions to the 1950 \"Whiz Kids\" Phillies helped them reach the World Series.",

            'R Smalley' => "Roy Smalley was part of a baseball family, providing solid production as a shortstop and later a designated hitter. His 163 career home runs showed power unusual for a shortstop.\n\nSmalley was an All-Star in 1979 when he hit 24 home runs for the Twins.\n\nHis versatility and solid production made him a valuable contributor.",

            'B Madlock' => "Bill Madlock won four batting titles with his compact swing, hitting .305 for his career with 163 home runs. His ability to make contact was exceptional.\n\nMadlock was a three-time All-Star who won titles with different teams.\n\nHis hand-eye coordination and bat control made him one of the best pure hitters of his era.",

            'D Demeter' => "Don Demeter was a solid outfielder who hit 163 career home runs while playing for several teams. His 29-homer season in 1962 showed legitimate power.\n\nDemeter was an All-Star whose contributions helped his teams compete.\n\nHis consistent production made him a valued contributor throughout his career.",

            'K Keltner' => "Ken Keltner made two of the most famous defensive plays in baseball history, ending Joe DiMaggio's 56-game hitting streak. His 163 career home runs came with elite defense at third base.\n\nKeltner was a seven-time All-Star known for his hot corner excellence.\n\nHis role in DiMaggio's streak ending ensures his place in baseball lore.",

            'D Easley' => "Damion Easley was a steady second baseman who hit 160 career home runs while providing solid defense. His 27-homer season in 1998 showed unexpected power.\n\nEasley was an All-Star who gave consistent effort throughout his 17-year career.\n\nHis professional approach made him a respected veteran.",

            'A Hill' => "Aaron Hill won a Silver Slugger award with the Blue Jays before injuries limited his effectiveness. His 160 career home runs came with solid defense at second base.\n\nHill was an All-Star in 2009 when he hit 36 home runs.\n\nHis peak seasons showed elite production from the second base position.",

            'J Gomes' => "Jonny Gomes was a beloved teammate whose intensity and clubhouse presence exceeded his 162 career home runs. He was part of two World Series championship teams.\n\nGomes's passion for the game made him a fan favorite everywhere he played.\n\nHis contributions to team culture were as valuable as his on-field production.",

            'A Ethier' => "Andre Ethier was a consistent outfielder for the Dodgers, hitting 162 career home runs while providing solid defense. His 30-game hitting streak in 2011 was remarkable.\n\nEthier was a two-time All-Star who played his entire career in Los Angeles.\n\nHis steady production and longevity made him a fan favorite at Dodger Stadium.",

            'T Steinbach' => "Terry Steinbach was a steady catcher who hit 162 career home runs while handling pitching staffs expertly. He was the MVP of the 1988 All-Star Game.\n\nSteinbach was a three-time All-Star who won a World Series with the A's in 1989.\n\nHis leadership behind the plate made him invaluable to his teams.",

            'K Hernandez' => "Keith Hernandez redefined the first base position with his defense, winning 11 consecutive Gold Gloves. His 162 career home runs were secondary to his exceptional glove work and bat control.\n\nHernandez was a five-time All-Star and 1979 co-MVP. He helped the Mets win the 1986 World Series.\n\nHis broadcasting career has made him one of baseball's most beloved personalities.",

            'P ?lvarez' => "Pedro Álvarez showed tremendous power potential, hitting 36 home runs in 2013 before defensive issues limited his career. His 160 career home runs came with prodigious raw power.\n\nÁlvarez was an All-Star whose batting practice sessions drew crowds.\n\nInjuries and defensive struggles cut short what could have been a more productive career.",

            'M San?' => "Miguel Sanó brought tremendous power to the Twins, hitting 30+ home runs multiple times. His strikeout-prone approach makes him a polarizing player.\n\nSanó's raw power is among the best in baseball when he connects.\n\nHis career exemplifies the modern power-or-nothing hitting approach.",

            'C Boyer' => "Clete Boyer was one of the best defensive third basemen in history, sacrificing offense for brilliant glove work. His 162 career home runs came while making spectacular plays.\n\nBoyer was an All-Star who won a Gold Glove with the Braves.\n\nHis defensive highlights remain impressive decades later.",

            'C Hart' => "Corey Hart was a power-hitting outfielder who hit 162 career home runs before knee injuries derailed his career. His 2010 season (31 HR) showed his potential.\n\nHart was a two-time All-Star whose right-handed power was impressive.\n\nInjuries cut short what was becoming an excellent career.",

            'J Samuel' => "Juan Samuel was a dynamic player who set rookie records for triples and at-bats. His 161 career home runs came with exceptional speed and versatility.\n\nSamuel was a three-time All-Star who played multiple positions.\n\nHis combination of power and speed made him exciting to watch.",

            'R Weeks Jr.' => "Rickie Weeks was a second baseman whose raw power was often interrupted by injuries. His 160 career home runs showed legitimate pop from the middle infield.\n\nWeeks was an All-Star in 2011 when healthy and productive.\n\nHis career showed how injuries can limit a player's potential.",

            'T Phillips' => "Tony Phillips was the ultimate super-utility player, providing value at multiple positions for 18 seasons. His 160 career home runs came with exceptional plate discipline.\n\nPhillips led the AL in walks once and drew over 100 walks four times.\n\nHis versatility and on-base ability made him valuable despite a modest power profile.",

            'B Melton' => "Bill Melton was the first White Sox player to lead the league in home runs, hitting 33 in 1971. His 160 career home runs established him as the team's power source.\n\nMelton was an All-Star whose power gave the Sox a legitimate middle-of-the-order threat.\n\nBack injuries shortened what could have been a longer career.",

            'F White' => "Frank White was one of the best defensive second basemen in history, winning eight Gold Gloves while hitting 160 career home runs. His acrobatic plays defined the position.\n\nWhite was a five-time All-Star who spent his entire 18-year career with the Royals.\n\nHis combination of defense and steady offense made him a franchise icon.",
        ];
    }
}

